name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.profile }}
      runs-on: ${{ matrix.os }}
      
      strategy:
        max-parallel: 1
        fail-fast: true
        matrix:
          include:

            - os: ubuntu-latest
              profile: Linux
              build-target: StandaloneLinux64
              modules: linux-mono

            - os: windows-latest
              profile: Windows
              build-target: StandaloneWindows64
              modules: windows-mono

    env:
      BLENDER_SHORT_VERSION: 4.5
      BLENDER_FULL_VERSION: 4.5.4

    steps:

      - uses: actions/checkout@v7
        
      - name: Setup Blender
        run: |
          wget https://download.blender.org/release/Blender$BLENDER_SHORT_VERSION/blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz
          tar -xf blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz
          echo "blender-$BLENDER_FULL_VERSION-linux-x64" >> "$GITHUB_PATH"      

      - uses: buildalon/unity-setup@v2.6.0
        with:
          version-file: ProjectSettings/ProjectVersion.txt
          modules: ${{ matrix.modules }}

      - uses: buildalon/activate-unity-license@v2.2.2
        with:
          license: Personal
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - uses: buildalon/unity-action@v3.1.0
        with:
          args: -quit -nographics -batchmode -executeMethod Build.${{ matrix.profile }}

      - name: Clean Directory
        working-directory: Build
        shell: bash
        run: rm -r *DoNotShip* || true

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.profile }}
          path: Build
          if-no-files-found: error